name: rote
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - pip=24.2
  - pip:
      - pydantic==2.9.2
      - structlog==24.4.0
      - tenacity==9.0.0
      - SQLAlchemy==2.0.35
      - pytest==8.3.3
      - pytest-cov==5.0.0
      - hypothesis==6.112.1
      - ruff==0.6.9
      - mypy==1.11.2
      - import-linter==2.1
