class RoteError(Exception): ...


class ContractError(RoteError): ...


class CanonicalisationError(ContractError): ...


class FingerprintError(ContractError): ...


class DomainError(RoteError): ...


class GeneratorError(DomainError): ...


class ToolError(DomainError): ...


class UnknownToolError(ToolError): ...


class ToolRequestError(ToolError): ...


class RecordNotFoundError(ToolError): ...


class CheckerError(DomainError): ...


class AgentError(RoteError): ...


class AgentProtocolError(AgentError): ...


class RecorderError(RoteError): ...


class PolicyError(RoteError):
    def __init__(self, verdict: object, reason: str) -> None:
        super().__init__(reason)
        self.verdict = verdict
        self.reason = reason


class CompilerError(RoteError): ...


class RegistryError(RoteError): ...


class ExecutorError(RoteError): ...


class GuardError(RoteError): ...
